apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-admin-secret
    namespace: prometheus
spec:
    secretTemplates:
        - name: grafana-admin-secret
          labels:
            app.kubernetes.io/name: grafana-admin-secret
          stringData:
            admin-user: ENC[AES256_GCM,data:8k5Onxk=,iv:1zwI7momrRqLYHOfybyC9KURFnjEV/sE+h96p9Usen4=,tag:fhSlyHVZO0vfj/f8KwLrtw==,type:str]
            admin-password: ENC[AES256_GCM,data:/B1ofStCX1fP,iv:axQjnT5fXMKh+HcsxnB7b/jLD2DZEmFpTxc0mXaCXiU=,tag:em567GE9cbx9UiXx48n3Sg==,type:str]
sops:
    age:
        - recipient: age13jkfzky97zmm4n738k3wy8leguhz6xy6xas9r4etnx2esyafadvqat4qve
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaGtjVWkrZ3RnYUNXbkxL
            S0ZFZDFpbDRpSE5zd2I2ZU8rTVVzdmZ2eUZFCkNXMWxqWnBrUE9xSk5xZE44a2d4
            NW4zSkUrUnpVQVFzVkMraUw1emdmNEkKLS0tIEkxOGl1alQrUkc3L0syaEZyTUpi
            VElBZ0tzMkNNdW91UWpPbW85REljU1UKQzvXQGC9CfEINSQAEG+WbD0lbY5FFmF1
            /Er2/JBPc+AMlMfZI3spTmC4O+24Y3KZJ4qdvhSy0OqboJB/o7R/OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T16:25:01Z"
    mac: ENC[AES256_GCM,data:4yq3fgzgjb92s4mjemdLtHq3aSTlBCaxudd5IAjKH8N6Owopbymo4YxQZfLPsNGBqc+RNVqoPHzGMZTCC/phhiz9HmrjxAtpmMDhh5pu0f3OdX7UlB91bBGNZIvIbxU8EwLXzoLDu5nDbN2t7/ZtlkYhtl7Kwv0dM5sHcMgMDZY=,iv:MvQ0sXygkNlRnx/9EWJon8IBz+BWS53S8du3hOkgiPo=,tag:JakUUUXsJnlmch863RSqnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
