zigbee2mqtt:
  statefulset:
    storage:
      enabled: true
      storageClassName: longhorn
    secrets:
      name: secret-yaml
    volumeMounts:
      - mountPath: /dev/ttyACM0
        name: usb-device
    volumes:
      - hostPath:
          path: /dev/ttyACM0
        name: usb-device
  zigbee2mqtt:
    mqtt:
      user: '!secret.yaml mqtt_user'
      password: '!secret.yaml mqtt_password'
      server: mqtt://192.168.0.60:1883
    serial:
      adapter: deconz
      baudrate: 38400
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: traefik-ipallowlan@kubernetescrd
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - host: zigbee.svc.madtech.cx
