zigbee2mqtt:
  statefulset:
    storage:
      enabled: true
      storageClassName: longhorn
    secrets:
      name: secret-yaml
    volumeMounts:
      - mountPath: /dev/usb
        name: usb-device
    volumes:
      - hostPath:
          path: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2496081-if00
        name: usb-device
  zigbee2mqtt:
    mqtt:
      user: '!secret.yaml mqtt_user'
      password: '!secret.yaml mqtt_password'
      server: mqtt://192.168.0.60:1883
    serial:
      port: /dev/usb
      adapter: deconz
      baudrate: 38400
    frontend:
      url: http://zigbee.svc.madtech.cx
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: traefik-ipallowlan@kubernetescrd
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - host: zigbee.svc.madtech.cx
        paths:
          - path: /
            pathType: ImplementationSpecific
          - path: /api
            pathType: ImplementationSpecific
    tls: null
