apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: httpbin
resources:
  - github.com/mccutchen/go-httpbin/kustomize
  - ingress.yaml
images:
  - name: mccutchen/go-httpbin:2.20

