---
# Only allow localhost and LAN access
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ipallowlan
spec:
  ipAllowList:
    ipStrategy:
      excludedIPs: "10.244.2.0"
    sourceRange:
      - 127.0.0.1/32
      - 192.168.0.0/24
